### ISSUE TITLE
Fails to parse email if lines are terminated with CRLF

### ISSUE THREAD

**Issue by glennzw** [jordan-wright/email#106]
If an email has lines terminated with CRLF the `NewEmailFromReader` function fails with the error:

`quotedprintable: invalid hex byte 0x0d`

(where 0x0d is the hex code for a CR)

I've only experienced this with one particular email from Google. To reproduce, run the `test_crlf.go` code against the attached emails (download here: [code_and_emails.zip](https://github.com/jordan-wright/email/files/4361072/code_and_emails.zip)).

The two .eml files appear identical, but one has CRLF line terminators and one does not.

```
➜  file *.eml
good_16087861c22a992efb54f73254b22052.eml: SMTP mail text, ASCII text
bad_fa25fc7fd80e89fe6531c535f4eb68dd.eml: SMTP mail text, ASCII text, with CRLF line terminators
```

```
➜  go run test_crlf.go good_16087861c22a992efb54f73254b22052.eml 
[+] Reading 'good_16087861c22a992efb54f73254b22052.eml'
[+] Email details:

	From: Google <noreply-utos@google.com>
	To: [safety.check.9001@gmail.com]
	Subject: Find out more about our updated Terms of Service
	HTML size: 20065
	Text size: 3936
```

```
➜  go run test_crlf.go bad_fa25fc7fd80e89fe6531c535f4eb68dd.eml 
[+] Reading 'bad_fa25fc7fd80e89fe6531c535f4eb68dd.eml'
[+] Email details:

[!] Unable to read email with Jordan's library: 
2020/03/20 16:21:51 quotedprintable: invalid hex byte 0x0d
exit status 1
```

Now we set the `removeCR` flag in the code to remove CRLF and the bad_ email file parses:

```
➜  go run test_crlf.go bad_fa25fc7

fd80e89fe6531c535f4eb68dd.eml 
[+] Reading 'bad_fa25fc7fd80e89fe6531c535f4eb68dd.eml'
[+] Removing carriage returns
[+] Email details:

	From: Google <noreply-utos@google.com>
	To: [safety.check.9001@gmail.com]
	Subject: Find out more about our updated Terms of Service
	HTML size: 20065
	Text size: 3936

```

N.B To make sure you have a 'good' copy of the two email files, their filenames are their MD5 sums:

```
md5sum *.eml 
16087861c22a992efb54f73254b22052  good_16087861c22a992efb54f73254b22052.eml
fa25fc7fd80e89fe6531c535f4eb68dd  bad_fa25fc7fd80e89fe6531c535f4eb68dd.eml
```

# Code:

```
package main

import (
	"bytes"
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"strings"

	"github.com/jordan-wright/email"
)

const removeCR = false

func main() {

	fmt.Printf("[+] Reading '%s'\n", os.Args[1])
	rawBody, err := ioutil.ReadFile(os.Args[1])
	if err != nil {
		fmt.Println("[!] Unable to read email")
		log.Fatal(err)
	}

	if removeCR {
		//Remove CR characters
		fmt.Println("[+] Removing carriage returns")
		tmp := string(rawBody)
		tmp = strings.ReplaceAll(tmp, "\r", "")
		rawBody = []byte(tmp)
	}

	rawBodyStream := bytes.NewReader(rawBody)

	fmt.Println("[+] Email details:\n")

	em, err := email.NewEmailFromReader(rawBodyStream) // Parse with @jordanwright's library
	if err != nil {
		fmt.Println("[!] Unable to read email with Jordan's library: ")
		log.Fatal(err)
	}

	fmt.Printf("\tFrom: %s\n\tTo: %s\n\tSubject: %s\n\tHTML size: %d\n\tText size: %d\n", em.From, em.To, em.Subject, len(em.HTML), len(em.Text))

}
```

**Comment by jordan-wright** [comment]
Hey @glennzw, thanks for the heads up on this! That's really interesting, since there's [a test](https://golang.org/src/mime/quotedprintable/reader_test.go#L60) for exactly this in the Go stdlib.

Everything that I can see suggests that CR's should be encoded as `=0D` so this feels like an invalid email. However, we should try to be flexible where possible so perhaps silently ignoring them is ideal. Let me play around a bit with this and I'll get back to you ASAP.

**Comment by maximelebastard** [comment]
Some news about this ?
Do you know any kind of workaround ?

**Comment by leucos** [comment]
I am experiencing this issue, and it is even weirder.

Headers are clean (i.e. no empty headers) and the email fails to parse. However, when I remove some headers, it can be decoded. It is reproducible (i.e. removing header X solves the issue).

But several headers impact decoding. For instance, let's say I have 3 headers A, B and C:

- A+B+C => problem
- B+C => no problem
- A+C => no problem
- A+B => problem

So removing header A solves the problem. Putting back A and removing B solves the problem too...
So it does not seem tied to _a specific_ header, but tied to "the whole thing".

Also, this particular email has `multipart/alternative`. If I set the `Content-Type` to `text/plain` and remove the HTML part, it solves the problem too.

I am out of ideas right now. If it can help, I can send you the eml that causes the problem. I can not send it here since, as you can guess, it is pretty hard to trim it down since it impacts the parsing result.

EDIT:

Made some progress: if I remove this particular header, the email always parse (whatever other header I remove):

```
ARC-Seal: i=1; a=rsa-sha256; cv=none; d=messagingengine.com; s=fm3; t=
    1597840747; b=XiHnwgBO+oCzzXKU5FGRM4H8+rRbaZMqfFF8hf2KCBymv0WeP0
    CJ5aeWhobHUPcxCwa5Z7bs3Zrtof0vGpwTgHDrrWw/CeZNWdkundSfODlpXk+tlm
    yQsCeWNvBdLgMkmsQBarE5IIV+2HQue+olo09VvfGs1VFrKKoXBs8iMIQU7Aw1WH
    M//uO+yq/c9fO47+GgKPcois3uxF1bTXm+V3OCuV0nORowk/qqY2gsy3ZhJswaeP
    iQdkyf591n/aU1IhIPeNx2aJG+lf+DUpn6y//A/lF70XqhHA2M2wAPTzy5Zxifm7
    IjFDKfgWoC+dHF1LecpYzNSpKkmpQODBI0cQ==
```

If I remove the second line (`1597840747; b=...`), the problem goes away. If I remove all lines besides the first one, the problem comes back.

Now if I add this header (or replace existing `Arc-Seal` header) in another (`text/plain` or `multipart/alternative`) email: no problem...

Also, in other failing emails, if I remove the `Arc-Seal` header it does not solves the issue.

Well, I wanted to shed some light on the problem, but I guess this comment makes it even more confusing :(

**Comment by leucos** [comment]
Made some progress. Here is the call stack right before the error happens:

![image](https://user-images.githubusercontent.com/158845/90767574-ba5cec80-e2ed-11ea-82d8-d361b296371f.png)

The related email part is this one:

```
HashiCorp Vault Specialist Dan McTeer shares his experiences and best pract=
ices regarding the people, processes, and internal adoption involved in an =
enterprise-scale HashiCorp Vault adoption.
```

When adding debugging in `mime/quotedprintable/reader.go` [line 111](https://golang.org/src/mime/quotedprintable/reader.go#L111), I see this:

```
...
current line is "ist Dan McTeer shares his experiences and best prac
...
current line is "ed in an =\renterprise-scale HashiCorp Vault adoption.\r\n"
```

Indeed, when hexdumping the original email, we have this:

```
00000fa0  73 20 61 6e 64 20 62 65  73 74 20 70 72 61 63 74  |s and best pract|
00000fb0  3d 0d 0a 69 63 65 73 20  72 65 67 61 72 64 69 6e  |=..ices regardin|
00000fc0  67 20 74 68 65 20 70 65  6f 70 6c 65 2c 20 70 72  |g the people, pr|
00000fd0  6f 63 65 73 73 65 73 2c  20 61 6e 64 20 69 6e 74  |ocesses, and int|
00000fe0  65 72 6e 61 6c 20 61 64  6f 70 74 69 6f 6e 20 69  |ernal adoption i|
00000ff0  6e 76 6f 6c 76 65 64 20  69 6e 20 61 6e 20 3d 0d  |nvolved in an =.|
00001000  0a 65 6e 74 65 72 70 72  69 73 65 2d 73 63 61 6c  |.enterprise-scal|
```

The "Dan McTeer" line ends with `=\r\n` (0x3d 0x0d 0x0a) while the problematic "involved" line ends with `=\r` (0x3d 0x0d).

So this boils down to the same problem you [described above](https://github.com/jordan-wright/email/issues/106#issuecomment-652685269) @jordan-wright

Here is an example fix to this issue using a chained `io.Reader`:

```go
package main

import (
	"fmt"
	"io"
	"os"

	"github.com/jordan-wright/email"
)

func main() {
	f, err := os.Open(os.Args[1])
	if err != nil {
		fmt.Fprintf(os.Stderr, "unable to open file %s: %v\n", os.Args[1], err)
		os.Exit(1)
	}
	defer f.Close()

	crr := newCrReader(f)

	_, err = email.NewEmailFromReader(crr)
	if err != nil {
		fmt.Fprintf(os.Stderr, "ERROR Parsing body: %v", err)
		os.Exit(1)
	}
}

type crReader struct {
	reader io.Reader
	equal  bool
}

func newCrReader(reader io.Reader) *crReader {
	return &crReader{reader: reader}
}

func (c *crReader) cr(r, next byte) byte {
	if r == '=' {
		// If this is an equal sign
		// let's take note so we can fix the next char of it is \r
		c.equal = true
		return r
	}

	if c.equal && r == '\r' && next != '\n' {
		// So last char was a '=' and now we have the infamous '\r'
		// Since it is not followed by '\n', this will be treated as invalid
		// Let's return '\n' instead (which is valid according to
		// https://golang.org/src/mime/quotedprintable/reader_test.go#L58)
		// [in golang 1.14.2]
		// We also do not reset a.equal yet, since there might be more \r coming
		return '\n'
	}

	// Let's switch back to DEFCON 5
	c.equal = false

	return r
}

func (c *crReader) Read(p []byte) (int, error) {
	n, err := c.reader.Read(p)
	if err != nil {
		return n, err
	}
	buf := make([]byte, n)
	for i := 0; i < n; i++ {
		var next byte
		if i < n-1 {
			next = p[i+1]
		}
		if char := c.cr(p[i], next); char != 0 {
			buf[i] = char
		}
	}

	copy(p, buf)
	return n, nil
}
```

**Comment by jordan-wright** [comment]
@glennzw interestingly enough, the "bad" email you provided is in the same boat. I made this little test to see if I could find a `\r` that wasn't followed by a `\n` and it passed fine:

```go
func TestNoCRLF(t *testing.T) {
	content, err := ioutil.ReadFile("email_google")
	if err != nil {
		t.Fatal(err)
	}
	set := false
	for _, b := range content {
		if set {
			if b != '\n' {
				t.Fatal("Bad email - only \r")
			}
			set = false
		}
		if b == '\r' {
			set = true
		}
	}
}
```

I'll keep digging since this definitely feels like a bug somewhere in the library (or below).

**Comment by glennzw** [comment]
As mentioned in https://github.com/jordan-wright/email/pull/122 this fix works perfect for my test, thanks @jordan-wright !

```
go run test_crlf.go bad_fa25fc7fd80e89fe6531c535f4eb68dd.eml
[+] Reading 'bad_fa25fc7fd80e89fe6531c535f4eb68dd.eml'
[+] Email details:

	From: Google <noreply-utos@google.com>
	To: [safety.check.9001@gmail.com]
	Subject: Find out more about our updated Terms of Service
	HTML size: 20400
	Text size: 3936
```
