### ISSUE TITLE
Strange Behaviour happens to Strange Caribbean golang tribe

### ISSUE THREAD

**Issue by rlertora** [jordan-wright/email#117]
**Hi.Sorry for this .We are not top notch guys/gals :maybe green 2 dashes belts from Guyana .**
1.We work with golang using Linux and use as default VSCODE as editor.We added ur fine pkg email and noted that the lint erased it from import.
2.No big deal ,but we noticed that this covered the fact that e := email.NewEmail() was NOT pointing to the pkg. 
3.We then used for a just in case approach the prehistoric vim from cl.
Here the erasure was not done (as no lint in town) but we got this
somecl .... :  "imported and not used: "github.com/jordan-wright/email"
somecl        vendor/xxxxr/passreco.go:135:15: email.newEmail undefined (type string has no field or method newEmail)

4.For some "feeling"  we created a 
func AnyTest(some string) string {

	e := email.NewEmail()
	e.From = "Jordan Wright <cccc@gmail.com>"
	e.To = []string{"destuser@gmail.com"}
.....
}
and called it from inside _the required  original functio_n 
sret := AnyTest("somedata")
**AND alas NO problem both using cl and vscode .And the resulting exec is fine .**
_With same humble spirit,we think we are doing something wrong .Any comment welcome._

J Lertora/ Gomon Aurelio
jlertora2020@gmail.com
UTC/GMT -4 hours same as US EST for the season

**Comment by jordan-wright** [comment]
Hi there!

I don't know that I can speak to why the linter would have removed the package from your imports. This sounds like a potential VSCode or code issue rather than an issue with the library itself.

That said, I'm going to go ahead and close this one out. If others start reporting the same issue, I can reopen and investigate further.

Thanks for getting in touch!
