### ISSUE TITLE
Any chance to send a html template?

### ISSUE THREAD

**Issue by bilicio** [jordan-wright/email#46]
I try to copy the html code from a template and sent but i didnt got the email and any errors at all. there is any trick to send formated html template mail?

thanks

**Comment by jordan-wright** [comment]
We expect the HTML as it's to be shown in the email. We don't support rendering HTML templates in our library, since there is already native support for HTML templates in Go: https://golang.org/pkg/html/template/

I recommend using the Go stdlib to generate your template and pass the result when creating a new email.
