### ISSUE TITLE
might be cool?

### ISSUE THREAD

**Issue by kristofer** [jordan-wright/email#5]
Might be cool if the Send mech had a way to do this in a go routine? to avoid blocking code using the package?

I would think we need some community guidance about whether the go routines should inside the packages or expected to be done by the users of the package...

opinion?

**Comment by arkn98** [comment]
Sorry for opening this up again. I'm working on some email-critical functionality. Currently to know whether a `Send(...)` failed (so that I can retry sending it again), I've to wait for it to return, which is long. Going by @dcoxall's suggestion, with the goroutine I'm ignoring the returned error.

So, is there some suggested way to run `Send(...)` inside a goroutine and predictably know whether it failed (for the purposes of resending)?
